### ISSUE TITLE
Make it easier for engineers to tell "abnormal" behaviour from the Merino dashboards

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#253] opened 2021-11-30 21:25 UTC
Engineers will be on pagerduty. At a given time, they'd need to tell and understand if any trend in the data is an anomaly.

This ticket is for defining guidelines and technical aids to determine what an anomaly is:

is it specific graphs deviating from their trends?

is it spikes in errors?

These guidelines should be added to the runbook, and technical aids to the relevant tools (such as Grafana).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1391)

**Comment by jklukas** [comment] 2022-01-05 17:31
This looks to be an orphaned duplicate of #233 and should be closed.

**Comment by jklukas** [comment] 2022-01-05 17:32
cc @ddurst

**Closed** 2022-01-05 17:35 UTC
